//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAdminTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int attendance_Id { get; set; }
        public System.DateTime date { get; set; }
        public int student_id { get; set; }
        public sbyte status { get; set; }
        public string remark { get; set; }
    
        public virtual student student { get; set; }
    }
}
