//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAdminTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public int exam_id { get; set; }
        public int exam_type_id { get; set; }
        public string name { get; set; }
        public System.DateTime start_date { get; set; }
    
        public virtual exam_type exam_type { get; set; }
    }
}
